FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

RUN apk add --no-cache curl

# Copiar build pronto (vem do artifact)
COPY public/ ./public/
COPY .next/standalone/frontend/ ./
COPY .next/static/ ./.next/static/

# Usuário não-root
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs && \
    chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
