name: Build, Docker and Deploy

on:
  push:
    branches: [main]

jobs:
  build-backend:
    uses: ./.github/workflows/main-build-backend.yml

  build-frontend:
    uses: ./.github/workflows/main-build-frontend.yml

  docker-backend:
    needs: build-backend
    uses: ./.github/workflows/main-docker-backend.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-frontend:
    needs: build-frontend
    uses: ./.github/workflows/main-docker-frontend.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-to-coolify:
    needs: [docker-backend, docker-frontend]
    uses: ./.github/workflows/main-deploy-coolify.yml
    secrets:
      COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
