name: Build, Docker and Deploy

on:
  push:
    branches: [main]

jobs:
  build-backend:
    uses: ./.github/workflows/main-build-backend.yml

  build-frontend:
    uses: ./.github/workflows/main-build-frontend.yml

  docker-backend:
    needs: build-backend
    uses: ./.github/workflows/main-docker-backend.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-frontend:
    needs: build-frontend
    uses: ./.github/workflows/main-docker-frontend.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-to-vps:
    needs: [docker-backend, docker-frontend]
    uses: ./.github/workflows/main-deploy-vps.yml
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      APP_KEY: ${{ secrets.APP_KEY }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
